name: AlchemistMMExtension
main: me.bedwarshurts.mmextension.AlchemistMMExtension
version: ${project.version}
api-version: 1.21
description: An extension for MythicMobs
author: bedwarshurts
depend: [MythicMobs]
softdepend: [MythicLib,MMOCore,MMOItems,PlaceholderAPI,ProtocolLib]
commands:
  playerspawnmythicmob:
    description: Spawns a MythicMob for a player
libraries:
  - net.kyori:adventure-api:4.16.0
  - net.kyori:adventure-platform-bukkit:4.3.2
  - net.kyori:adventure-text-minimessage:4.16.0
  - net.kyori:adventure-text-serializer-gson:4.16.0
  - org.mariuszgromada.math:MathParser.org-mXparser:6.1.0